App channel revision (#9)
* app channel revision
mostly adaptions that were brought over from the revised payment channel example to attain similarities between these examples

* updated ci

* fix: register app

* fix: wait for app deployment

* deploy: panic on error

* OpenAppChannel: Improve documentation

* OpenAppChannel: Might be cleaner to return pointer

* CI: Move app channels before collateralized channels

* CI: don't fail if container is not running

* moved grid comment

* added comments to channel.go

* Readme: Removed ganache --gasPrice

* ForceSet: Added for dispute case

* fix: TicTacToeApp.sol winner index

* main.go: examplary dispute case

* AppChannel renamed  toTicTacToeChannel

* CI: removed --gasPrice

* Client: payment -> app in comments

* Scenario: Dispute trigger

* Revert "fix: TicTacToeApp.sol winner index"

This reverts commit 77e2aa794ee9d4f3700f7afe14f62b7579727ac8.

* fix: TicTacToeApp.sol winner index requirement

* Scenario: Removed time.sleep
and made dispute case standard

* Payment Channel: OpenChannel now return a pointer
as in the app channel example

* Deployment: Changed gas limit
to be closer to the TicTacToe contract requirement (which is currently around 1034584)

* Minor changes through review

Update app-channel/channel.go
Update app-channel/util.go
Update app-channel/main.go
Update app-channel/client/client.go
Update app-channel/client/channel.go

Co-authored-by: matthiasgeihs <62935430+matthiasgeihs@users.noreply.github.com>

Co-authored-by: Matthias Geihs <matthias@perun.network>
Co-authored-by: matthiasgeihs <62935430+matthiasgeihs@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -44,7 +44,20 @@ jobs:
           KEY_BOB: '0xf63d7d8e930bccd74e93cf5662fde2c28fd8be95edb70c73f1bdd863d07f412e'
           BALANCE: '10000000000000000000'
         run: |
-          docker run --rm --name ganache --detach --publish 8545:8545 ${{ env.gananache-image }} --account $KEY_DEPLOYER,$BALANCE --account $KEY_ALICE,$BALANCE --account $KEY_BOB,$BALANCE --blockTime=5 --gasPrice=0
+          docker run --rm --name ganache --detach --publish 8545:8545 ${{ env.gananache-image }} --account $KEY_DEPLOYER,$BALANCE --account $KEY_ALICE,$BALANCE --account $KEY_BOB,$BALANCE --blockTime=5
+          sleep 5
+          go run .
+          docker stop ganache
+
+      - name: App Channel
+        working-directory: app-channel
+        env:
+          KEY_DEPLOYER: '0x79ea8f62d97bc0591a4224c1725fca6b00de5b2cea286fe2e0bb35c5e76be46e'
+          KEY_ALICE: '0x1af2e950272dd403de7a5760d41c6e44d92b6d02797e51810795ff03cc2cda4f'
+          KEY_BOB: '0xf63d7d8e930bccd74e93cf5662fde2c28fd8be95edb70c73f1bdd863d07f412e'
+          BALANCE: '10000000000000000000'
+        run: |
+          docker run --rm --name ganache --detach --publish 8545:8545 ${{ env.gananache-image }} --account $KEY_DEPLOYER,$BALANCE --account $KEY_ALICE,$BALANCE --account $KEY_BOB,$BALANCE --blockTime=5
           sleep 5
           go run .
           docker stop ganache
@@ -55,12 +68,4 @@ jobs:
           GANACHE_CMD: "docker run --name ganache --rm --publish 8545:8545 ${{ env.gananache-image }}"
         run: |
           go test -v -timeout 60s .
-          docker stop ganache
-
-      - name: App Channel
-        working-directory: app-channel
-        env:
-          GANACHE_CMD: "docker run --name ganache --rm --publish 8545:8545 ${{ env.gananache-image }}"
-        run: |
-          go test -v -timeout 60s .
-          docker stop ganache
+          docker stop ganache || true # Cleanup
